version: 2
jobs:
  checkout_code:
    working_directory: ~/sayfizz
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  unit_tests:
    working_directory: ~/sayfizz
    docker:
      - image: circleci/python:3.6.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unittest
          command: python fizzbuzztest.py

  build_image:
    working_directory: ~/sayfizz
    docker:
      - image: circleci/python:3.6.1
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: |
          docker build -t roseth/sayfizz:latest .
          echo $DOCKER_PASS | docker login -u roseth --password-stdin
          docker push roseth/sayfizz:latest

workflows:
  version: 2
  say-fizz-pipeline:
    jobs:
      - checkout_code
      - unit_tests:
          requires:
            - checkout_code
      - build_image:
          requires:
            - unit_tests
